# Generated by Django 4.2 on 2023-04-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Med',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('perscribed', models.DateField()),
                ('expiration', models.DateField()),
                ('instructions', models.TextField(max_length=250)),
            ],
        ),
    ]
